// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMozoQr.Infrastructure.Data;

#nullable disable

namespace SistemaMozoQr.Infrastructure.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260703160045_AddSolidDbEngineeringAndNewRoles")]
    partial class AddSolidDbEngineeringAndNewRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.DashboardWidgetConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WidgetKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DashboardWidgetConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000001"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000002"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000003"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000004"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000005"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000006"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000007"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000008"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000009"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000010"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000011"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000012"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000013"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000014"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000015"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000016"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000017"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000018"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000019"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000020"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000021"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000022"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000023"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000024"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000025"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000026"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000027"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000028"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000029"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000030"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000031"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000032"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000033"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000034"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000035"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000036"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000037"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000038"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000039"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000040"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000041"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000042"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            WidgetKey = "PeakHours"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000043"),
                            Activo = true,
                            Orden = 1,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "KPI_Ventas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000044"),
                            Activo = true,
                            Orden = 2,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "KPI_Pedidos"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000045"),
                            Activo = true,
                            Orden = 3,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "KPI_Llamados"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000046"),
                            Activo = true,
                            Orden = 4,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "KPI_Alertas"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000047"),
                            Activo = true,
                            Orden = 5,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "StaffPerformance"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000048"),
                            Activo = true,
                            Orden = 6,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "TopTables"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-000000000049"),
                            Activo = true,
                            Orden = 7,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            WidgetKey = "PeakHours"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaAPI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioInvolucrado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("MenuCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000001"),
                            Emoji = "🍔",
                            Nombre = "Comidas"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Emoji = "🍷",
                            Nombre = "Bebida con alcohol"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            Emoji = "🥤",
                            Nombre = "Bebida fria"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            Emoji = "🍰",
                            Nombre = "Postre"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Emoji = "☕",
                            Nombre = "Bebidas calientes"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Emoji = "🥗",
                            Nombre = "Entradas",
                            ParentCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000012"),
                            Emoji = "🍝",
                            Nombre = "Platos",
                            ParentCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-000000000013"),
                            Emoji = "🍞",
                            Nombre = "Panes",
                            ParentCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000001")
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MenuCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("RestauranteId", "Nombre");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000014"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Agua Mineral",
                            Precio = 1500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000015"),
                            Activo = true,
                            Categoria = "Platos",
                            Nombre = "Milanesa con Papas Fritas",
                            Precio = 8500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000016"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Nombre = "Pizza Muzzarella",
                            Precio = 9000m,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000017"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Descripcion = "Clásica porción fina",
                            Nombre = "Pizza Servilleta",
                            Precio = 250m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000018"),
                            Activo = true,
                            Categoria = "Clásicos",
                            Nombre = "Panchos con mostaza",
                            Precio = 350m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000019"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Cerveza Patricia 1L",
                            Precio = 450m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000020"),
                            Activo = true,
                            Categoria = "Cafetería",
                            Nombre = "Café de Especialidad",
                            Precio = 280m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000021"),
                            Activo = true,
                            Categoria = "Dulces",
                            Nombre = "Medialunas Rellenas",
                            Precio = 320m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000022"),
                            Activo = true,
                            Categoria = "Salados",
                            Nombre = "Tostado de Campo",
                            Precio = 450m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000023"),
                            Activo = true,
                            Categoria = "Pastas",
                            Nombre = "Ravioles de espinaca con salsa",
                            Precio = 800m,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000024"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Nombre = "Pizza Margherita",
                            Precio = 700m,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000025"),
                            Activo = true,
                            Categoria = "Cervezas",
                            Nombre = "Cerveza IPA Cordon",
                            Precio = 350m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000026"),
                            Activo = true,
                            Categoria = "Comidas",
                            Nombre = "Hamburguesa Completa con Fritas",
                            Precio = 650m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000027"),
                            Activo = true,
                            Categoria = "Comidas",
                            Nombre = "Papas Cheddar y Bacon",
                            Precio = 450m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000011"),
                            Activo = true,
                            Categoria = "Comidas",
                            Descripcion = "Salsa de tomate, muzzarella y abundante pepperoni premium",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000012"),
                            Nombre = "Pizza Pepperoni",
                            Precio = 750m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000012"),
                            Activo = true,
                            Categoria = "Comidas",
                            Descripcion = "Doble carne smash, queso cheddar, panceta crujiente y salsa secreta",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000012"),
                            Nombre = "Hamburguesa Especial",
                            Precio = 680m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000013"),
                            Activo = true,
                            Categoria = "Comidas",
                            Descripcion = "Papas horneadas con romero y alioli casero",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000011"),
                            Nombre = "Papas Rústicas",
                            Precio = 350m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000014"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Descripcion = "Medida pinta, sabor lúpulo intenso",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000002"),
                            Nombre = "Cerveza IPA Artesanal",
                            Precio = 420m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000015"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Descripcion = "Botella individual fría",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000003"),
                            Nombre = "Refresco Cola 500ml",
                            Precio = 250m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000016"),
                            Activo = true,
                            Categoria = "Postres",
                            Descripcion = "Con helado de crema americana",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000004"),
                            Nombre = "Volcán de Chocolate",
                            Precio = 480m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000017"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Descripcion = "Con espuma de leche y canela",
                            MenuCategoryId = new Guid("cccccccc-cccc-cccc-cccc-000000000005"),
                            Nombre = "Café Capuccino",
                            Precio = 290m,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAcceso")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MontoConsumo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MozoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenQR")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MozoId");

                    b.HasIndex("TokenQR");

                    b.HasIndex("RestauranteId", "Numero")
                        .IsUnique();

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA1_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("11111000-0000-0000-0000-000000000002"),
                            Estado = 0,
                            Numero = 2,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA2_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("22222000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TokenQR = "MESA1_R2_QR"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000001"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_1",
                            Ubicacion = "Mesa principal entrada"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000002"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Numero = 2,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_2",
                            Ubicacion = "Mesa redonda en el centro"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000003"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Numero = 3,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_3",
                            Ubicacion = "Box familiar derecha"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000004"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Numero = 4,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_4",
                            Ubicacion = "Ambiente intimo al fondo"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000005"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Numero = 5,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_5",
                            Ubicacion = "Sector fumadores terraza"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000006"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_1",
                            Ubicacion = "Ventana luminosa"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000007"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Numero = 2,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_2",
                            Ubicacion = "Sofa grande"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000008"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Numero = 3,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_3",
                            Ubicacion = "Rincon lectura"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000009"),
                            Estado = 0,
                            MozoId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TokenQR = "ITALIA_QR_1",
                            Ubicacion = "Mesa romantica"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000010"),
                            Estado = 0,
                            MozoId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Numero = 2,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TokenQR = "ITALIA_QR_2",
                            Ubicacion = "Mesa central"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000011"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_1",
                            Ubicacion = "Barra 1"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000012"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000003"),
                            Numero = 2,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_2",
                            Ubicacion = "Mesa Alta"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000013"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000005"),
                            Numero = 3,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_3",
                            Ubicacion = "Sector Pool"
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            MozoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            TokenQR = "TURESTAURANTE_QR_1",
                            Ubicacion = "Terraza Vista Calle"
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000002"),
                            Estado = 0,
                            MozoId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Numero = 2,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            TokenQR = "TURESTAURANTE_QR_2",
                            Ubicacion = "Salón Principal Ventana"
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000003"),
                            Estado = 0,
                            MozoId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Numero = 3,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            TokenQR = "TURESTAURANTE_QR_3",
                            Ubicacion = "Salón Centro"
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000004"),
                            Estado = 0,
                            MozoId = new Guid("70000000-0000-0000-0000-000000000004"),
                            Numero = 4,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            TokenQR = "TURESTAURANTE_QR_4",
                            Ubicacion = "VIP Box"
                        },
                        new
                        {
                            Id = new Guid("77777000-0000-0000-0000-000000000005"),
                            Estado = 0,
                            MozoId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Numero = 5,
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            TokenQR = "TURESTAURANTE_QR_5",
                            Ubicacion = "Barra Alta"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedMozoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAcceso")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("MesaId", "Estado");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconoPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentRestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentRestauranteId");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🍽️",
                            Nombre = "El Gran Sabor"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🥩",
                            Nombre = "La Parrilla de Juan"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🌭",
                            Nombre = "La Pasiva"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "☕",
                            Nombre = "La Merienda"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🍕",
                            Nombre = "Bella Italia"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🍺",
                            Nombre = "Cordon Beer"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "🍕",
                            Nombre = "TuRestaurante"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mozo del restaurante",
                            Nombre = "Mozo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Administrador del restaurante",
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Super Administrador global del sistema",
                            Nombre = "SuperAdmin"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Personal de cocina",
                            Nombre = "Cocina"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Cajero del restaurante",
                            Nombre = "Caja"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Portal de selección para Mozos",
                            Nombre = "MozoPortal"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "CleanupJobIntervalHours",
                            Value = "24"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.UserPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            NombreCompleto = "Super Admin",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 3,
                            RolId = 3,
                            Username = "supergino"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999998"),
                            NombreCompleto = "Tizi Super Admin",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 3,
                            RolId = 3,
                            Username = "tizisuper"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Admin Sabor",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 2,
                            RolId = 2,
                            Username = "adminsabor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Mozo Sabor",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozosabor"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Admin Roma",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 2,
                            RolId = 2,
                            Username = "adminroma"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Mozo Roma",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozoroma"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000000"),
                            NombreCompleto = "Admin Pasiva",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 2,
                            RolId = 2,
                            Username = "adminlapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Mozo 1",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo1lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Mozo 2",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo2lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            NombreCompleto = "Mozo 3",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo3lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            NombreCompleto = "Mozo 4",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo4lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            NombreCompleto = "Mozo 5",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo5lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            NombreCompleto = "Mozo 6",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo6lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            NombreCompleto = "Mozo 7",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo7lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            NombreCompleto = "Mozo 8",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo8lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            NombreCompleto = "Mozo 9",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo9lapasiva"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            NombreCompleto = "Mozo 10",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo10lapasiva"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000000"),
                            NombreCompleto = "Admin Merienda",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 2,
                            RolId = 2,
                            Username = "adminlamerienda"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Lucia",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1,
                            RolId = 1,
                            Username = "lucialamerienda"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Mateo",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mateolamerienda"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            NombreCompleto = "Sofia",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1,
                            RolId = 1,
                            Username = "sofialamerienda"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000000"),
                            NombreCompleto = "Admin Bella Italia",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 2,
                            RolId = 2,
                            Username = "adminbellaitalia"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Mario",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mariobellaitalia"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Luigi",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 1,
                            RolId = 1,
                            Username = "luigibellaitalia"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000000"),
                            NombreCompleto = "Admin Cordon Beer",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 2,
                            RolId = 2,
                            Username = "admincordonbeer"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Bartender 1",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1,
                            RolId = 1,
                            Username = "bartender1cordonbeer"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Bartender 2",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1,
                            RolId = 1,
                            Username = "bartender2cordonbeer"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            NombreCompleto = "Mesero 1",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mesero1cordonbeer"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            NombreCompleto = "Mesero 2",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mesero2cordonbeer"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            NombreCompleto = "Mesero 3",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mesero3cordonbeer"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000000"),
                            NombreCompleto = "Admin TuRestaurante",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 2,
                            RolId = 2,
                            Username = "admin_turestaurante"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000005"),
                            NombreCompleto = "Caja TuRestaurante",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 5,
                            RolId = 5,
                            Username = "caja_turestaurante"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000006"),
                            NombreCompleto = "Cocina TuRestaurante",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 4,
                            RolId = 4,
                            Username = "cocina_turestaurante"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000007"),
                            NombreCompleto = "Portal Mozo TuRestaurante",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 6,
                            RolId = 6,
                            Username = "mozo_portal_turestaurante"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            NombreCompleto = "Juan Pérez",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo_juan"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            NombreCompleto = "Pedro Gómez",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo_pedro"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            NombreCompleto = "María López",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo_maria"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            NombreCompleto = "Ana Silva",
                            PasswordHash = "$2a$11$QZiZ0I01OY9YHmu28SD3puogxLv8eZr0bbrj8pUvL/eoVHeZRUgJm",
                            RestauranteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rol = 1,
                            RolId = 1,
                            Username = "mozo_ana"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetallesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MesaNumero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MozoNombre")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId", "FechaHora");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuCategory", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId");

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mozo");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId");

                    b.HasOne("SistemaMozoQr.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId");

                    b.Navigation("MenuItem");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("ParentRestauranteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.UserPushSubscription", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Venta", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Mesas");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
