// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMozoQr.Infrastructure.Data;

#nullable disable

namespace SistemaMozoQr.Infrastructure.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260526223216_Initial_V2_MultiTenant_Sqlite")]
    partial class Initial_V2_MultiTenant_Sqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaAPI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioInvolucrado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Agua M.",
                            Precio = 1500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            Categoria = "Platos",
                            Nombre = "Milanesa",
                            Precio = 8500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Nombre = "Muzzarella",
                            Precio = 9000m,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoAcceso")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MozoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenQR")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MozoId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA1_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Estado = 0,
                            Numero = 2,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA2_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TokenQR = "MESA1_R2_QR"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedMozoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            ColorPrincipal = "#1E3A8A",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "El Gran Sabor"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            ColorPrincipal = "#B91C1C",
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "La Parrilla de Juan"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "CleanupJobIntervalHours",
                            Value = "24"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Email = "super@gino.com",
                            NombreCompleto = "",
                            PasswordHash = "$2a$11$Z6n8yP..T08G5k5xOQ5B2ea6bM3oE8o1F5o.U4U.Qo.K5Zq6B.z.m",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Email = "admin@sabor.com",
                            NombreCompleto = "",
                            PasswordHash = "$2a$11$A9snZ9y7jC9Z6s8013gbAuj8k7rpdEhUM0GCmHrXao6vxqnhNC8ta",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Email = "mozo@sabor.com",
                            NombreCompleto = "",
                            PasswordHash = "$2a$11$A9snZ9y7jC9Z6s8013gbAuj8k7rpdEhUM0GCmHrXao6vxqnhNC8ta",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Email = "admin@roma.com",
                            NombreCompleto = "",
                            PasswordHash = "$2a$11$A9snZ9y7jC9Z6s8013gbAuj8k7rpdEhUM0GCmHrXao6vxqnhNC8ta",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Email = "mozo@roma.com",
                            NombreCompleto = "",
                            PasswordHash = "$2a$11$A9snZ9y7jC9Z6s8013gbAuj8k7rpdEhUM0GCmHrXao6vxqnhNC8ta",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 1
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId");

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mozo");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Mesas");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
