// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMozoQr.Infrastructure.Data;

#nullable disable

namespace SistemaMozoQr.Infrastructure.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260527224751_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Accion")
                        .IsRequired()
                        ;

                    b.Property<string>("Detalles")
                        .IsRequired()
                        ;

                    b.Property<string>("Entidad")
                        .IsRequired()
                        ;

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        ;

                    b.Property<DateTime>("FechaHora")
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.Property<string>("UsuarioEmail")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("FechaHora")
                        ;

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.Property<string>("RutaAPI")
                        .IsRequired()
                        ;

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        ;

                    b.Property<string>("UsuarioInvolucrado")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activo")
                        ;

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<decimal>("Precio")
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000014"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Agua M.",
                            Precio = 1500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000015"),
                            Activo = true,
                            Categoria = "Platos",
                            Nombre = "Milanesa",
                            Precio = 8500m,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000016"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Nombre = "Muzzarella",
                            Precio = 9000m,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000017"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Descripcion = "Clásica porción fina",
                            Nombre = "Pizza Servilleta",
                            Precio = 250m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000018"),
                            Activo = true,
                            Categoria = "Clásicos",
                            Nombre = "Panchos con mostaza",
                            Precio = 350m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000019"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Cerveza Patricia 1L",
                            Precio = 450m,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000020"),
                            Activo = true,
                            Categoria = "Cafetería",
                            Nombre = "Café de Especialidad",
                            Precio = 280m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000021"),
                            Activo = true,
                            Categoria = "Dulces",
                            Nombre = "Medialunas Rellenas",
                            Precio = 320m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000022"),
                            Activo = true,
                            Categoria = "Salados",
                            Nombre = "Tostado de Campo",
                            Precio = 450m,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000023"),
                            Activo = true,
                            Categoria = "Pastas",
                            Nombre = "Ravioles de espinaca",
                            Precio = 800m,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000024"),
                            Activo = true,
                            Categoria = "Pizzas",
                            Nombre = "Pizza Margherita",
                            Precio = 700m,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000025"),
                            Activo = true,
                            Categoria = "Cervezas",
                            Nombre = "IPA Cordon",
                            Precio = 350m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000026"),
                            Activo = true,
                            Categoria = "Comidas",
                            Nombre = "Hamburguesa Completa",
                            Precio = 650m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000027"),
                            Activo = true,
                            Categoria = "Comidas",
                            Nombre = "Papas Cheddar y Bacon",
                            Precio = 450m,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("CodigoAcceso")
                        .HasMaxLength(10)
                        ;

                    b.Property<int>("Estado")
                        ;

                    b.Property<Guid?>("MozoId")
                        ;

                    b.Property<int>("Numero")
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.Property<string>("TokenQR")
                        ;

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(250)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("MozoId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA1_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("11111000-0000-0000-0000-000000000002"),
                            Estado = 0,
                            Numero = 2,
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TokenQR = "MESA2_R1_QR"
                        },
                        new
                        {
                            Id = new Guid("22222000-0000-0000-0000-000000000001"),
                            Estado = 0,
                            Numero = 1,
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TokenQR = "MESA1_R2_QR"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000001"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_1",
                            Ubicacion = "Mesa principal entrada"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000002"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Numero = 2,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_2",
                            Ubicacion = "Mesa redonda en el centro"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000003"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Numero = 3,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_3",
                            Ubicacion = "Box familiar derecha"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000004"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Numero = 4,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_4",
                            Ubicacion = "Ambiente intimo al fondo"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000005"),
                            Estado = 0,
                            MozoId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Numero = 5,
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TokenQR = "PASIVA_QR_5",
                            Ubicacion = "Sector fumadores terraza"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000006"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_1",
                            Ubicacion = "Ventana luminosa"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000007"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000002"),
                            Numero = 2,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_2",
                            Ubicacion = "Sofa grande"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000008"),
                            Estado = 0,
                            MozoId = new Guid("40000000-0000-0000-0000-000000000003"),
                            Numero = 3,
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TokenQR = "MERIENDA_QR_3",
                            Ubicacion = "Rincon lectura"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000009"),
                            Estado = 0,
                            MozoId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TokenQR = "ITALIA_QR_1",
                            Ubicacion = "Mesa romantica"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000010"),
                            Estado = 0,
                            MozoId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Numero = 2,
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TokenQR = "ITALIA_QR_2",
                            Ubicacion = "Mesa central"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000011"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Numero = 1,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_1",
                            Ubicacion = "Barra 1"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000012"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000003"),
                            Numero = 2,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_2",
                            Ubicacion = "Mesa Alta"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-000000000013"),
                            Estado = 0,
                            MozoId = new Guid("60000000-0000-0000-0000-000000000005"),
                            Numero = 3,
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            TokenQR = "BEER_QR_3",
                            Ubicacion = "Sector Pool"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("AssignedMozoId")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("Details")
                        .IsRequired()
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.Property<string>("Status")
                        .IsRequired()
                        ;

                    b.Property<int>("TableId")
                        ;

                    b.Property<string>("Type")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("Estado")
                        ;

                    b.Property<DateTime>("Fecha")
                        ;

                    b.Property<Guid>("MesaId")
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("Cantidad")
                        ;

                    b.Property<Guid>("MenuItemId")
                        ;

                    b.Property<Guid>("PedidoId")
                        ;

                    b.Property<decimal>("PrecioUnitario")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activo")
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        ;

                    b.Property<string>("IconoPrincipal")
                        ;

                    b.Property<string>("LogoUrl")
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        ;

                    b.Property<Guid?>("ParentRestauranteId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ParentRestauranteId");

                    b.ToTable("Restaurantes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "???",
                            Nombre = "El Gran Sabor"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "??",
                            Nombre = "La Parrilla de Juan"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "??",
                            Nombre = "La Pasiva"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "?",
                            Nombre = "La Merienda"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "??",
                            Nombre = "Bella Italia"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Activo = true,
                            FechaCreacion = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconoPrincipal = "??",
                            Nombre = "Cordon Beer"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        ;

                    b.Property<string>("Value")
                        .IsRequired()
                        ;

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Key = "CleanupJobIntervalHours",
                            Value = "24"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        ;

                    b.Property<Guid>("RestauranteId")
                        ;

                    b.Property<int>("Rol")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Email = "super@gino.com",
                            NombreCompleto = "Super Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Email = "admin@sabor.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "mozo@sabor.com",
                            NombreCompleto = "Mozo",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Email = "admin@roma.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Email = "mozo@roma.com",
                            NombreCompleto = "Mozo",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000000"),
                            Email = "admin@lapasiva.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Email = "mozo1@lapasiva.com",
                            NombreCompleto = "Mozo 1",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Email = "mozo2@lapasiva.com",
                            NombreCompleto = "Mozo 2",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Email = "mozo3@lapasiva.com",
                            NombreCompleto = "Mozo 3",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Email = "mozo4@lapasiva.com",
                            NombreCompleto = "Mozo 4",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Email = "mozo5@lapasiva.com",
                            NombreCompleto = "Mozo 5",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Email = "mozo6@lapasiva.com",
                            NombreCompleto = "Mozo 6",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Email = "mozo7@lapasiva.com",
                            NombreCompleto = "Mozo 7",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Email = "mozo8@lapasiva.com",
                            NombreCompleto = "Mozo 8",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Email = "mozo9@lapasiva.com",
                            NombreCompleto = "Mozo 9",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Email = "mozo10@lapasiva.com",
                            NombreCompleto = "Mozo 10",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000000"),
                            Email = "admin@lamerienda.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Email = "lucia@lamerienda.com",
                            NombreCompleto = "Lucia",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Email = "mateo@lamerienda.com",
                            NombreCompleto = "Mateo",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Email = "sofia@lamerienda.com",
                            NombreCompleto = "Sofia",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000000"),
                            Email = "admin@bellaitalia.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Email = "mario@bellaitalia.com",
                            NombreCompleto = "Mario",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Email = "luigi@bellaitalia.com",
                            NombreCompleto = "Luigi",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000000"),
                            Email = "admin@cordonbeer.com",
                            NombreCompleto = "Admin",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 0
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Email = "bartender1@cordonbeer.com",
                            NombreCompleto = "Bartender 1",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Email = "bartender2@cordonbeer.com",
                            NombreCompleto = "Bartender 2",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Email = "mesero1@cordonbeer.com",
                            NombreCompleto = "Mesero 1",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Email = "mesero2@cordonbeer.com",
                            NombreCompleto = "Mesero 2",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Email = "mesero3@cordonbeer.com",
                            NombreCompleto = "Mesero 3",
                            PasswordHash = "$2a$11$.bOXz4wVNeNh2KImM1g79O/TmlQsZ44j0ZvBrSSp2GRn0pFys2jpa",
                            RestauranteId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Rol = 1
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.ErrorLog", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId");

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mozo");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MesaTask", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("ParentRestauranteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Restaurante", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Restaurante", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Mesas");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
