// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMozoQr.Infrastructure.Data;

#nullable disable

namespace SistemaMozoQr.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    [Migration("20260517173432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37ccadfb-4f6e-415f-8f50-f38d52ab07d5"),
                            Activo = true,
                            Categoria = "Bebidas",
                            Nombre = "Agua M.",
                            Precio = 1500m
                        },
                        new
                        {
                            Id = new Guid("7bf63217-308d-480d-8d6f-4e972d14be48"),
                            Activo = true,
                            Categoria = "Platos Principales",
                            Nombre = "Milanesa con Papas",
                            Precio = 8500m
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid?>("MozoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("TokenQR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("MozoId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e458adbe-2dba-4cbc-83f5-b2119368acb1"),
                            Estado = 0,
                            Numero = 1,
                            TokenQR = "MESA1_QR_TOKEN"
                        },
                        new
                        {
                            Id = new Guid("09166452-1e63-4b0a-91e2-d81f4ef6bdc8"),
                            Estado = 0,
                            Numero = 2,
                            TokenQR = "MESA2_QR_TOKEN"
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f40eca01-3eea-4248-bcf0-27800ef6eac7"),
                            Email = "admin@r.com",
                            NombreCompleto = "Administrador",
                            PasswordHash = "$2a$11$8xTbO1kBpjLsgQxuvoeE3uAAAXrB2I4mYhhPHyGwdcFSlcgd7BwMu",
                            Rol = 0
                        });
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId");

                    b.Navigation("Mozo");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SistemaMozoQr.Domain.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaMozoQr.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaMozoQr.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
